src/config/urls.py
from django.contrib import admin
from django.urls import path, include, reverse, reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    path('users/', include('users.urls')),
    path('', RedirectView.as_view(url=reverse_lazy('news:list')))
]

src/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.NewsListView.as_view(), name='list'),
    path('create/', views.NewsCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.NewsUpdateView.as_view(), name='update'),
]

src/users/urls.py
from django.urls import path, include, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/auth/login.html',
                                                redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

src/news/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class News(models.Model):
    title = models.CharField(max_length=250, verbose_name='Название')
    text = models.TextField(verbose_name='Текст')

    author = models.ForeignKey(User, on_delete=models.PROTECT)

    creation_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
        ordering = ['-update_date', '-creation_date']

    def __str__(self):
        return f'[{self.id}] {self.title}'

    def get_absolute_url(self):
        return reverse('news:update', kwargs={'pk': self.id})

src/users/models.py
from django.db import models

# Create your models here.

src/news/views.py
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth import mixins

from . import models


class NewsListView(generic.ListView):
    model = models.News
    template_name = 'news/news_list.html'
    paginate_by = 5


class NewsCreateView(mixins.LoginRequiredMixin, generic.CreateView):
    model = models.News
    fields = ['title', 'text']
    success_url = reverse_lazy('news:list')
    template_name = 'news/news_form.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class NewsUpdateView(mixins.LoginRequiredMixin, generic.UpdateView):
    model = models.News
    fields = ['title', 'text']
    success_url = reverse_lazy('news:list')
    template_name = 'news/news_form.html'

    def get_object(self, queryset=None):
        obj: models.News = super(NewsUpdateView, self).get_object(queryset)

        if self.request.user.is_staff or obj.author == self.request.user:
            return obj
        raise Http404

src/users/views.py
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/auth/signup.html'

    def form_valid(self, form):
        response = super(SignUpView, self).form_valid(form)
        messages.success(self.request, 'Вы успешно зарегестрировалась! Используйте свои данные для входа')
        return response

src/news/templates/news/news_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
    {% if object %}
        {{ object.title }}
    {% else %}
        Создание новости
    {% endif %}

{% endblock %}

{% block content %}
    {% if object %}
        <h1>Редактирование новости</h1>
    {% else %}
        <h1>Создание новости</h1>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <div>
            {{ form|crispy }}
            <button class="btn btn-success" type="submit">Сохранить</button>
        </div>
    </form>
{% endblock %}

src/news/templates/news/news_list.html
{% extends "base.html" %}

{% block title %}
    Новости
{% endblock %}

{% block content %}
    <h1>Новости</h1>
    {% if user.is_authenticated %}
        <div class="mt-3 mb-3">
            <a href="{% url 'news:create' %}" class="btn btn-primary">Создать новость</a>
        </div>
    {% endif %}
    <div>
        {% for news in news_list %}
            <div class="row">
                <div class="col-md-12">
                    <div class="card mt-2 mb-2">
                        <div class="card-body">
                            <h5 class="card-title mb-0">{{ news.title }}</h5>
                            <div class="mb-2" style="color: gray">
                                <div>
                                    <small>
                                        <span>Дата публикации: {{ news.creation_date|date:'d.m.Y H:i' }}</span>
                                    </small>
                                </div>
                                <div>
                                    <small>
                                        <span>Автор: {{ news.author }}</span>
                                    </small>
                                </div>
                            </div>
                            <p class="card-text">{{ news.text }}</p>
                            {% if user.is_staff or news.author == user %}
                                <a href="{{ news.get_absolute_url }}">Редактировать</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% include 'components/pagination.html' %}
    </div>
{% endblock %}

src/templates/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %} | Django security News</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

<div class="container pt-5 pb-4" style="min-height: calc(100vh - 80px);">
    {% include 'messages.html' %}

    {% block content %}
    {% endblock %}
</div>

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
</body>
</html>

src/templates/components/pagination.html
{% if is_paginated %}
    <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">Назад</a>
                {% endif %}
                <span class="page-current">
                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">Далее</a>
                {% endif %}
            </span>
    </div>
{% endif %}

src/templates/footer.html
<footer class="bg-light text-center text-lg-start">
    <div class="text-center p-3">
        <span id="footerYear"></span> Created by:
        <a class="text-dark" target="_blank" href="https://github.com/bolanebyla/">bolanebyla</a>
    </div>
</footer>

<script>
    document.getElementById('footerYear').innerHTML = new Date().getFullYear();
</script>

src/templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-dismissible fade show {{ message.tags }} m-2" id="msg" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Закрыть"></button>
        </div>
    {% endfor %}
{% endif %}

src/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">DjangoSecurityNews</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'news:list' %}">
                        Новости
                    </a>
                </li>

                {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'admin:index' %}">
                            Админка
                        </a>
                    </li>
                {% endif %}

            </ul>
            <form class="d-flex" role="search">
                {% if user.is_authenticated %}
                    <div class="pe-3">
                        {{ user }}
                    </div>
                {% endif %}
                <div class="mr-2">
                    {% if user.is_authenticated %}
                        <a href="{% url 'users:logout' %}">Выход</a>
                    {% else %}
                        <a href="{% url 'users:login' %}">Войти</a>
                        <span> / </span>
                        <a href="{% url 'users:signup' %}">Регистрация</a>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</nav>

<div class="mb-4"></div>